file_upload y cambios en Linea.c
Nannajpg/c-interactive-dictionary-syan pull request #2
Opened 2022-02-04 00:14 UTC by Nannajpg

2022-02-04 00:52 UTC, Hector1567XD requested changes

2022-02-04 00:52 UTC, Hector1567XD commented on core/include/file_upload.h
> +  int existe_archivo(char fname[]);                          //verifica si existe el archivo
```suggestion
  int existeArchivo(char fname[]);                          //verifica si existe el archivo  
```

2022-02-04 00:52 UTC, Hector1567XD commented on core/file_upload.c
> +int existe_archivo(char fname[]) {
```suggestion
int existeArchivo(char fname[]) { 
```

2022-02-04 00:52 UTC, Hector1567XD commented on core/file_upload.c
> +int cont_Lineas(char fname[]){
```suggestion
int contarLineasArchivo(char fname[]){
```

2022-02-04 00:52 UTC, Hector1567XD commented on core/file_upload.c
> +struct Linea ** cargar_archivo(char fname[],long int size, int num) {
```suggestion
struct Linea ** cargarArchivo(char fname[],long int size, int num) {
```

2022-02-04 00:52 UTC, Hector1567XD commented on core/file_upload.c
> +                //printf("%s\n",getSecondSentenceBySeparator((c+2),' '));
```suggestion
```

2022-02-04 00:52 UTC, Hector1567XD commented on core/file_upload.c
> +
```suggestion
struct Linea ** cargarArchivoPorNombre(char fname[]) {
   int size = fsize(fname);
   int num = contarLineasArchivo(fname);
   return cargarArchivo(fname, size, num);
}
```

2022-02-04 00:52 UTC, Hector1567XD commented on core/include/file_upload.h
> +  long int fsize(char fname[]);                              //tamano del archivo
```suggestion
```
No la vamos a utilizar, solo tu la usas para uso interno pero es indiferente del resto del proyecto por lo que es una funcion privada

2022-02-04 00:52 UTC, Hector1567XD commented on core/include/file_upload.h
> +  struct Linea* crearLinea(char *palabra,char * palabraRel,int esSinonimo);
```suggestion
```
👀

2022-02-04 00:52 UTC, Hector1567XD commented on core/include/file_upload.h
> +  int cont_Lineas(char fname[]);
```suggestion
  int contarLineasArchivo(char fname[]);
```

2022-02-04 00:52 UTC, Hector1567XD commented on core/include/file_upload.h
> +  struct Linea ** cargar_archivo(char fname[],long int size,int num);  //leer el archivo
```suggestion
  struct Linea ** cargarArchivoPorNombre(char fname[]);  //leer el archivo
```

2022-02-04 00:52 UTC, Hector1567XD commented on core/include/file_upload.h
> +  struct Linea ** cargar_archivo(char fname[],long int size,int num);  //leer el archivo
Tu internamente puedes resolver el tamaño del archivo y su cantidad de lineas, no deberiamos nosotros utilizar tus propias funciones para darte a ti misma eso, esta correcion es para darnos a nosotros la interface mas simple posible

2022-02-04 00:52 UTC, Hector1567XD commented on core/file_upload.c
> +#include <stdio.h>
Cambia la ruta de este archivo a
`/core/lib/file-load.c`

2022-02-04 00:52 UTC, Hector1567XD commented on core/include/file_upload.h
> +#ifndef file_upload_h
Cambia la ruta de este archivo a
`/core/lib/include/file-load.h`

Recuerda actualizar el respectivo MakeFile

2022-02-04 00:52 UTC, Hector1567XD commented on tad/include/linea.h
>  #endif /* linea_h */
Nice :3 🥇

2022-02-04 00:52 UTC, Hector1567XD commented on tad/linea.c
> +  //pNode->palabra = palabra;
```suggestion
```

2022-02-04 00:52 UTC, Hector1567XD commented on tad/include/linea.h
>      // Metodos basicos del TDA linea
```suggestion
    // Metodos basicos del TDA linea
    
    struct Linea* crearLinea(char *palabra,char * palabraRel,int esSinonimo);
```
Esto va aqui xd

2022-02-04 01:02 UTC, Hector1567XD requested changes

2022-02-04 01:02 UTC, Hector1567XD commented on core/file_upload.c
> +#include "../tad/include/linea.h"
```suggestion
#include "../../tad/include/linea.h"
```

2022-02-04 01:02 UTC, Hector1567XD commented on core/file_upload.c
> +#include "../utils/include/string-formating-utils.h"
```suggestion
#include "../../utils/include/string-formating-utils.h"
```

2022-02-04 21:32 UTC, Yisustxz approved these changes
you are the best!! :D

2022-02-05 01:05 UTC, Hector1567XD approved these changes

2022-02-05 01:08 UTC, merged